spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://hanamarket-rds.cy5zap5los6d.ap-northeast-2.rds.amazonaws.com:3306/hmarket'
    username: 'admin'
    password: 'hana123!'
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${spring.datasource.url}
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}

#  datasource:
#    write:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: ${datasource-write-jdbc-url}
#      username: ${datasource-write-username}
#      password: ${datasource-write-password}
#      hikari:
#        minimum-idle: 5
#        maximum-pool-size: 100
#        max-lifetime: 28800000
#        keepalive-time: 60000
#        idle-timeout: 60000
#    read:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: ${datasource-read-jdbc-url}
#      username: ${datasource-read-username}
#      password: ${datasource-read-password}
#      hikari:
#        minimum-idle: 5
#        maximum-pool-size: 100
#        max-lifetime: 28800000
#        keepalive-time: 60000
#        idle-timeout: 60000


#  h2:
#    console:
#      enabled: false
#      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: user
#    password:
#
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true