### 프로파일 설정 하지 않을시,Local 로 설정
spring.profiles.active: local

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: 'jdbc:mysql://hana-market-rdb.ccb5xjcxwfiy.ap-northeast-2.rds.amazonaws.com:3306/hmarket'
      username: 'admin'
      password: 'hana123!'
      hikari:
        minimum-idle: 5
        maximum-pool-size: 100
        max-lifetime: 28800000
        keepalive-time: 60000
        idle-timeout: 60000
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: 'jdbc:mysql://hana-market-read.ccb5xjcxwfiy.ap-northeast-2.rds.amazonaws.com/hmarket'
      username: 'admin'
      password: 'hana123!'
      hikari:
        minimum-idle: 5
        maximum-pool-size: 100
        max-lifetime: 28800000
        keepalive-time: 60000
        idle-timeout: 60000
